name: 'latent'

batch_size: 128
num_workers: 8
data_dir: '.'
latent_data: '.'
sample_shape: [256, 16, 8, 8]
fid_sample_shape: [500, 16, 8, 8]
n_dataset_samples: 50000
input_shape: [3, 32, 32]
plot_type: 'grid'
img_resolution: 32
in_channels: 3
out_channels: 3